  def label = "build"
  podTemplate(label: label, yaml: """
  apiVersion: v1
  kind: Pod
  metadata:
    labels:
      name: build
  spec:
    serviceAccount: jenkins-admin
    containers:
    - name: build
      image: dpthub/dpt7-jenkins-agent
      command:
      - cat
      tty: true
  """
  ) {
      node (label) {

          stage ('Checkout SCM'){
            git credentialsId: 'git', url: 'https://dptrealtime@bitbucket.org/dptrealtime/eos-admin-deployment.git', branch: 'dev'
          }

          stage ('Helm Chart') {
            container('build') {
                withCredentials([usernamePassword(credentialsId: 'jfrog', usernameVariable: 'username', passwordVariable: 'password')]) {
                      sh '/usr/local/bin/helm repo add dpt7-helm-local  https://edproject.jfrog.io/artifactory/dpt7-helm-local --username $username --password $password'
                      sh "/usr/local/bin/helm repo update"
                      sh "/usr/local/bin/helm upgrade --install micro-services-admin  --namespace dev -f values.yaml dpt7-helm-local/micro-services-admin"
                      sh "/usr/local/bin/helm list -a --namespace dev"
              }
          }
          }
      }
  }